artifact_location: file:///Users/ajayghimire/Desktop/lezea_mlops/LEZEA_MLOPS1/mlflow_runs/0
creation_time: 1756055244824
experiment_id: '0'
last_update_time: 1756055244824
lifecycle_stage: active
name: Default
