# Prometheus Configuration for LeZeA MLOps

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lezea-mlops'
    environment: 'production'
    datacenter: 'local'

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ["localhost:9093"]

rule_files:
  - "alerts.yml"
  #- "recording_rules.yml"

scrape_configs:
  # LeZeA app
  - job_name: 'lezea-mlops'
    static_configs: [{ targets: ['localhost:8000'] }]
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    honor_labels: true
    params: { format: ['prometheus'] }
    metric_relabel_configs:
    
      - source_labels: [__name__]
        regex: 'lezea_.*'
        target_label: component
        replacement: 'lezea-mlops'

  # Prometheus self
  - job_name: 'prometheus'
    static_configs: [{ targets: ['localhost:9090'] }]
    metrics_path: '/metrics'

  # Node exporter
  - job_name: 'node-exporter'
    static_configs: [{ targets: ['localhost:9100'] }]
    metrics_path: '/metrics'

  # NVIDIA GPU exporter (optional)
  - job_name: 'nvidia-gpu'
    static_configs: [{ targets: ['localhost:9835'] }]
    metrics_path: '/metrics'
    honor_labels: true

  # MLflow
  - job_name: 'mlflow'
    static_configs: [{ targets: ['localhost:5000'] }]
    scrape_interval: 30s
    metrics_path: '/metrics'
    params: { format: ['prometheus'] }
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'mlflow_.*'
        target_label: service
        replacement: 'mlflow'

  # PostgreSQL exporter (optional)
  - job_name: 'postgresql'
    static_configs: [{ targets: ['localhost:9187'] }]
    metrics_path: '/metrics'

  # MongoDB exporter (optional)
  - job_name: 'mongodb'
    static_configs: [{ targets: ['localhost:9216'] }]
    metrics_path: '/metrics'

  # MinIO (optional)
  - job_name: 'minio'
    static_configs: [{ targets: ['localhost:9000'] }]
    scrape_interval: 30s
    metrics_path: '/minio/v2/metrics/cluster'
    scheme: http
    honor_labels: true
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'minio_.*'
        target_label: service
        replacement: 'minio'

  # Training processes via file_sd (optional)
  - job_name: 'training-processes'
    file_sd_configs:
      - files: ['training_targets.json']
        refresh_interval: 30s
    scrape_interval: 10s
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'python_gc_.*'
        action: drop

  # Blackbox exporter (optional)
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params: { module: [http_2xx] }
    static_configs:
      - targets:
        - http://localhost:5000/health
        - http://localhost:8000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params: { module: [tcp_connect] }
    static_configs:
      - targets:
        - localhost:5432
        - localhost:27017
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
